services:
    frontend:
        image: etag-frontend-i:latest
        container_name: etag-frontend
        restart: always
        build:
            context: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend
        env_file:
            - .env

    backend:
        image: etag-backend-i:latest
        container_name: etag-backend
        restart: always
        build:
            context: ./backend
        env_file:
            - .env

    database:
        image: postgres:latest
        container_name: etag-database
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

networks:
    default:
        driver: bridge

